import type Database from 'better-sqlite3';
import { createStudentsTables } from './students.schema';
import { createAcademicTables, seedSubjectsAndTopics } from './academic.schema';
import { createSurveysTables, seedSurveysDefaultTemplates } from './surveys.schema';
import { createCounselingTables } from './counseling.schema';
import { createCoachingTables } from './coaching.schema';
import { createSettingsTables } from './settings.schema';
import { createUsersTable, seedAdminUser } from './users.schema';
import { createSchoolsTables, seedDefaultSchools } from './schools.schema';
import { createAnalyticsCacheTable } from './analytics-cache.schema';
import { initStandardizedProfileTables } from './standardized-profile.schema';
import { createCareerGuidanceTables, seedCareerProfiles } from './career-guidance.schema';
import { createProfileSyncTables } from './profile-sync.schema';
import { createAISuggestionsTable } from './ai-suggestions.schema';
import { createAIAnalysisTables } from './ai-analysis.schema';
import { createAnalyticsSnapshotTable } from './analytics-snapshot.schema';
import { createAuditLogsTable } from './audit-logs.schema';
import { createNotificationTables } from './notifications.schema';
import { createEarlyWarningTables } from './early-warning.schema';
import { createStudyPlanTables } from './study-plan.schema';
import { createDailyInsightsTables } from './daily-insights.schema';
import { createExamManagementTables, seedExamData, createAdvancedExamTables } from './exam-management.schema';
import { createWebVitalsTable } from './web-vitals.schema';
import { createHolisticProfileTables } from './holistic-profile.schema';
import { createGuidanceStandardsTables, seedGuidanceStandards } from './guidance-standards.schema';
import { createGuidanceTipsTable, migrateGuidanceTipsTable } from './guidance-tips.schema';

export function initializeDatabaseSchema(db: Database.Database): void {
  createSchoolsTables(db);
  seedDefaultSchools(db);
  createUsersTable(db);
  seedAdminUser(db);
  createStudentsTables(db);
  createAcademicTables(db);
  seedSubjectsAndTopics(db);
  createSurveysTables(db);
  seedSurveysDefaultTemplates(db);
  createCounselingTables(db);
  createCoachingTables(db);
  createSettingsTables(db);
  createAnalyticsCacheTable(db);
  initStandardizedProfileTables(db);
  createCareerGuidanceTables(db);
  seedCareerProfiles(db);
  createProfileSyncTables(db);
  createAISuggestionsTable(db);
  createAIAnalysisTables(db);
  createAnalyticsSnapshotTable(db);
  createAuditLogsTable(db);
  createNotificationTables(db);
  createEarlyWarningTables(db);
  createStudyPlanTables(db);
  createDailyInsightsTables(db);
  createExamManagementTables(db);
  seedExamData(db);
  createAdvancedExamTables(db);
  createWebVitalsTable(db);
  createHolisticProfileTables(db);
  createGuidanceStandardsTables(db);
  seedGuidanceStandards(db);
  migrateGuidanceTipsTable(db);
  createGuidanceTipsTable(db);
}
